"""Init

Revision ID: 2d1449028001
Revises: 
Create Date: 2023-12-15 14:17:58.057363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d1449028001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.add_column('image_m2m_tag', sa.Column('image', sa.Integer(), nullable=True))
    op.drop_constraint('image_m2m_tag_note_fkey', 'image_m2m_tag', type_='foreignkey')
    op.create_foreign_key(None, 'image_m2m_tag', 'images', ['image'], ['id'], ondelete='CASCADE')
    op.drop_column('image_m2m_tag', 'note')
    op.add_column('images', sa.Column('public_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('user_role', sa.String(), nullable=False))
    op.drop_column('users', 'crated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('crated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'user_role')
    op.drop_column('users', 'created_at')
    op.drop_column('images', 'public_id')
    op.add_column('image_m2m_tag', sa.Column('note', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'image_m2m_tag', type_='foreignkey')
    op.create_foreign_key('image_m2m_tag_note_fkey', 'image_m2m_tag', 'images', ['note'], ['id'], ondelete='CASCADE')
    op.drop_column('image_m2m_tag', 'image')
    op.drop_table('user_roles')
    # ### end Alembic commands ###
