"""Revision after merge

Revision ID: 566c5deefb11
Revises: 833cbc1bec21
Create Date: 2023-12-11 10:56:35.460374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '566c5deefb11'
down_revision: Union[str, None] = '833cbc1bec21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_m2m_tag', sa.Column('note', sa.Integer(), nullable=True))
    op.drop_constraint('image_m2m_tag_image_fkey', 'image_m2m_tag', type_='foreignkey')
    op.create_foreign_key(None, 'image_m2m_tag', 'images', ['note'], ['id'], ondelete='CASCADE')
    op.drop_column('image_m2m_tag', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_m2m_tag', sa.Column('image', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'image_m2m_tag', type_='foreignkey')
    op.create_foreign_key('image_m2m_tag_image_fkey', 'image_m2m_tag', 'images', ['image'], ['id'], ondelete='CASCADE')
    op.drop_column('image_m2m_tag', 'note')
    # ### end Alembic commands ###
