"""Small changes

Revision ID: ccbb26753da7
Revises: 91da35268c52
Create Date: 2023-12-10 13:56:01.197564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccbb26753da7'
down_revision: Union[str, None] = '91da35268c52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_m2m_tag', sa.Column('image', sa.Integer(), nullable=True))
    op.drop_constraint('image_m2m_tag_note_fkey', 'image_m2m_tag', type_='foreignkey')
    op.create_foreign_key(None, 'image_m2m_tag', 'images', ['image'], ['id'], ondelete='CASCADE')
    op.drop_column('image_m2m_tag', 'note')
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.add_column('image_m2m_tag', sa.Column('note', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'image_m2m_tag', type_='foreignkey')
    op.create_foreign_key('image_m2m_tag_note_fkey', 'image_m2m_tag', 'images', ['note'], ['id'], ondelete='CASCADE')
    op.drop_column('image_m2m_tag', 'image')
    # ### end Alembic commands ###
